# If true, this indicates that the symbol should always have

# a symbol nested within its nesting area(s).

always_nest = false



# If true, this indicates that the symbol should always

# be nested inside another symbol's nesting area.

always_be_nested = false



# If true, this indicates that the symbol should never

# be nested inside another symbol's nesting area.

never_be_nested = false



# If true, this indicates that the symbol nested on this

# symbol’s nesting area should have its colors inverted.

invert_nested = true