export const STROKE_REPLACEMENT_COLOR = "#000000";
export const FILL_REPLACEMENT_COLOR = "#ffffff";

export const TAIL_ATTACHMENT_COLOR = "#ff0000";
export const LEGS_ATTACHMENT_COLOR = "#ffff00";
export const ARMS_ATTACHMENT_COLOR = "#00ff00";
export const HORNS_ATTACHMENT_COLOR = "#00ffff";
export const CROWN_ATTACHMENT_COLOR = "#0000ff";

export const NESTING_BOUNDING_BOX_COLOR = "#ff00ff";

export const NON_VISUAL_COLORS = new Set([
  TAIL_ATTACHMENT_COLOR,
  LEGS_ATTACHMENT_COLOR,
  ARMS_ATTACHMENT_COLOR,
  HORNS_ATTACHMENT_COLOR,
  CROWN_ATTACHMENT_COLOR,
  NESTING_BOUNDING_BOX_COLOR,
]);
