# If true, this indicates that the symbol should always have
# a symbol nested within its nesting area(s).

always_nest = false



# If true, this indicates that the symbol should always
# be nested inside another symbol's nesting area.
always_be_nested = false


# If true the symbol rotation direction will be clockwise
rotate_clockwise = true